-- Setup Snowflake Environment for Data Quality Monitoring
-- Create Database and Schema
CREATE DATABASE IF NOT EXISTS DATA_QUALITY_DB;
CREATE SCHEMA IF NOT EXISTS DATA_QUALITY_DB.MONITORING;

-- Create table to store data quality rules
CREATE TABLE IF NOT EXISTS DATA_QUALITY_DB.MONITORING.DQ_RULES (
    RULE_ID VARCHAR(50) PRIMARY KEY,
    RULE_NAME VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT,
    DATASET_NAME VARCHAR(100) NOT NULL,
    SQL_QUERY TEXT NOT NULL,
    SEVERITY VARCHAR(20) DEFAULT 'MEDIUM',
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Create table to store data quality check results
CREATE TABLE IF NOT EXISTS DATA_QUALITY_DB.MONITORING.DQ_RESULTS (
    RESULT_ID VARCHAR(50) PRIMARY KEY,
    RULE_ID VARCHAR(50) REFERENCES DATA_QUALITY_DB.MONITORING.DQ_RULES(RULE_ID),
    EXECUTION_TIME TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    TOTAL_RECORDS INTEGER,
    FAILED_RECORDS INTEGER,
    FAILURE_RATE FLOAT,
    STATUS VARCHAR(20), -- 'PASS', 'FAIL', 'ERROR'
    ERROR_MESSAGE TEXT
);

-- Example Rule Insertion
INSERT INTO DATA_QUALITY_DB.MONITORING.DQ_RULES (RULE_ID, RULE_NAME, DESCRIPTION, DATASET_NAME, SQL_QUERY, SEVERITY)
VALUES 
('NULL_CHECK_EMAIL', 'Email Null Check', 'Checks for null emails in the customer dataset', 'CUSTOMERS', 'SELECT COUNT(*) FROM CUSTOMERS WHERE EMAIL IS NULL', 'HIGH'),
('UNIQUE_CHECK_ID', 'ID Uniqueness Check', 'Checks for duplicate IDs in the orders dataset', 'ORDERS', 'SELECT COUNT(ORDER_ID) - COUNT(DISTINCT ORDER_ID) FROM ORDERS', 'CRITICAL');
